### ISSUE TITLE
ERROR: Command error: stateDir when using Score-client to upload files with manifest file

### ISSUE THREAD

**Issue by lindaxiang** [overture-stack/score#117]
1. Song payload was uploaded and saved. The analysis can be searched by analysis_id: 
https://song.cancercollaboratory.org/studies/BTCA-SG/analysis/8cd6d332-c86e-11e5-8fbf-b2f52362275d
2. The manifest file is also generated with the content:
8cd6d332-c86e-11e5-8fbf-b2f52362275d		
445609bb-bf14-518a-8c3e-9fac0b7f4431	33e7645453f9236cad23205e2ea43fae.bam.bai	9291d0c860e10ed110e51c0ad31aa44d
92852e46-72cf-5bbf-88c8-ef2ad84135d2	33e7645453f9236cad23205e2ea43fae.bam	33e7645453f9236cad23205e2ea43fae

3. But When using `score-client` to upload the files specified in the manifest file using the command:
`score-client --profile collab upload --manifest ~/pcawg_validation/8cd6d332-c86e-11e5-8fbf-b2f52362275d.normal.json.manifest`

The following error message is returned:
2018-09-14 11:42:50,172 [main] INFO  o.i.d.s.c.c.UploadCommand - Uploading file '33e7645453f9236cad23205e2ea43fae.bam.bai'...
2018-09-14 11:42:50,327 [main] ERROR o.i.d.s.c.ClientMain - Unknown error:
java.lang.NullPointerException: stateDir
        at org.icgc.dcc.storage.client.state.TransferState.getObjectStateDir(TransferState.java:58)
        at org.icgc.dcc.storage.client.upload.UploadStateStore.fetchUploadId(UploadStateStore.java:93)
        at org.icgc.dcc.storage.client.upload.s3.S3UploadService.checkProgress(S3UploadService.java:150)
        at org.icgc.dcc.storage.client.upload.s3.S3UploadService.resumeIfPossible(S3UploadService.java:134)
        at org.icgc.dcc.storage.client.upload.s3.S3UploadService.upload(S3UploadService.java:91)
        at org.icgc.dcc.storage.client.command.UploadCommand.uploadFile(UploadCommand.java:116)
        at org.icgc.dcc.storage.client.command.UploadCommand.execute(UploadCommand.java:95)
        at org.icgc.dcc.storage.client.ClientMain.run(ClientMain.java:136)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:784)
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
        at org.icgc.dcc.storage.client.ClientMain.main(ClientMain.java:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
2018-09-14 11:42:50,334 [Thread-1] INFO  o.s.c.a.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@1bc6a36e: startup date [Fri Sep 14 11:42:47 EDT 2018]; root of context hierarchy

**Comment by lindaxiang** [comment]
FYI: the score-client has the version:
ICGC Storage Client
  Version: 1.4.0
  Built:   11.03.2016 @ 11:23:08 EST

**Comment by junjun-zhang** [comment]
@rtisma can you please take a look?

**Comment by rtisma** [comment]
@lindaxiang can you please replace the filename in the manifest, with the ABSOLUTE file path. then rerun. The next version of song-client and python-sdk (not released yet) will automatically populate the manifest files with absolute file paths.

**Comment by rtisma** [comment]
upload completed after changing manifest file paths to be absolute paths. issue has been resolved
