### ISSUE TITLE
compatibility of score 1.4.0 or icgc-storage-client 1.0.23 on Ubuntu 18.04

### ISSUE THREAD

**Issue by jmimico** [overture-stack/score#123]
We've received a ticket [COLHLP-588] from Lincoln who is attempting to use icgc-storage-client 1.0.23 on Ubuntu 18.04 and gets large error messages during successful downloads of a requested file:

ubuntu@lincolns-vm:~$ /usr/local/lib/icgc-storage-client-1.0.23/bin/icgc-storage-client --profile collab download --object-id 26ed125c-bc28-552c-b82d-1de2561b3911 --output-layout bundle --output-dir input
Starting...[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:580)
at java.lang.Integer.valueOf(Integer.java:766)
at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:233)
at jline.UnixTerminal.<init>(UnixTerminal.java:64)
at jline.UnixTerminal.<init>(UnixTerminal.java:49)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
(... much more...)

**Comment by jmimico** [comment]
This appears to affect score-client-1.4.0 too.

Environment is Ubuntu 18.04 with oracle-java8
# dpkg -l | grep -i java
ii  java-common                     0.63ubuntu1~02                    all          Base package for Java runtimes
ii  libjs-jquery                    3.2.1-1                           all          JavaScript library for dynamic web applications
ii  oracle-java8-installer          8u191-1~webupd8~1                 all          Oracle Java(TM) Development Kit (JDK) 8
ii  oracle-java8-set-default        8u191-1~webupd8~1                 all          Set Oracle JDK 8 as default Java

**Comment by rtisma** [comment]
fixed in #124 

The next score-client release will contain this change, however the error does not affect the execution of the core business logic, just the presentation on the terminal. 

To use this change immediatly, please use the `edge` docker score-client 
https://score-docs.readthedocs.io/en/latest/introduction.html#client

`docker pull overture/score:edge`
