### ISSUE TITLE
Error when trying to download an unpublished object_id but able to download complete file

### ISSUE THREAD

**Issue by hknahal** [overture-stack/score#128]
I was attempting to download an unpublished object_id. When I ran the following command, it returned an error message, but I was able to download the complete BAM file at the end.

Here is the command I used:
`./score-client-1.4.0/bin/score-client download --object-id 45dfcd17-8e80-53fc-b400-cc8b583dae05 --output-dir ~/score-client_downloads`

Here are SONG (unpublished) payloads:
SONG payload in Collab: https://song.cancercollaboratory.org/studies/OV-AU/analysis/EGAR00001083635

SONG payload in AWS: https://virginia.song.icgc.org/studies/OV-AU/analysis/EGAR00001083635

Here is the output when I ran score-client (Not sure if the error is related to downloading an unpublished object_id):

Starting...[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:233)
	at jline.UnixTerminal.<init>(UnixTerminal.java:64)
	at jline.UnixTerminal.<init>(UnixTerminal.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at jline.TerminalFactory.getFlavor(TerminalFactory.java:209)
	at jline.TerminalFactory.create(TerminalFactory.java:100)
	at jline.TerminalFactory.get(TerminalFactory.java:184)
	at jline.TerminalFactory.get(TerminalFactory.java:190)
	at bio.overture.score.client.cli.Terminal.<init>(Terminal.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1148)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1051)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1128)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1056)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:751)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at bio.overture.score.client.ClientMain.main(ClientMain.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)

Downloading...                                                                  
--------------------------------------------------------------------------------
[1/1] Downloading object: 45dfcd17-8e80-53fc-b400-cc8b583dae05 (ea8d859f36b403045467d7000858dc7f.S0417_20100702_1_Frag.nopd.nobc.bam)
--------------------------------------------------------------------------------
100% [##################################################]  Parts: 99/99, Checksum: 100%, Write/sec: 0B/s, Read/sec: 17.4M/s    
Finalizing...
Total execution time:       24.33 min
Total bytes read    :  26,569,449,887
Total bytes written :               0
OkDone.

**Comment by hknahal** [comment]
Just some more info. I tried to publish the analysis (https://song.cancercollaboratory.org/studies/OV-AU/analysis/publish/EGAR00001083635?ignoreUndefinedMd5=false), but it returned an error related to "missing storage objects", which is strange, because I was able to download the file using score-client


{
  "errorId": "missing.storage.objects",
  "httpStatusCode": 409,
  "httpStatusName": "CONFLICT",
  "requestUrl": "http://song.cancercollaboratory.org/studies/OV-AU/analysis/publish/EGAR00001083635?ignoreUndefinedMd5=false",
  "datetime": "2018-11-16T22:28:51.107Z[Etc/UTC]",
  "timestamp": 1542407331107,
  "message": "[AnalysisService::missing.storage.objects] - The following storage objectIds must be uploaded to the storage server before the analysisId EGAR00001083635 can be published: FileEntity(super=Metadata(info={}), objectId=ba02b8eb-bc07-5d6e-9334-d46f168fa0f0, studyId=OV-AU, analysisId=EGAR00001083635, fileName=bundle.EGAR00001083635.xml, fileSize=7290, fileType=XML, fileMd5sum=8e52c54e7af07691f3a11fbbb2f8412d, fileAccess=open),FileEntity(super=Metadata(info={}), objectId=45dfcd17-8e80-53fc-b400-cc8b583dae05, studyId=OV-AU, analysisId=EGAR00001083635, fileName=ea8d859f36b403045467d7000858dc7f.S0417_20100702_1_Frag.nopd.nobc.bam, fileSize=26569449887, fileType=BAM, fileMd5sum=ea8d859f36b403045467d7000858dc7f, fileAccess=controlled)",
  "debugMessage": "N/A",
  "stackTrace": [
    "bio.overture.song.core.exceptions.SongError.createSongError(SongError.java:133)",
    "bio.overture.song.core.exceptions.SongError.createSongError(SongError.java:129)",
    "bio.overture.song.core.exceptions.SongError.createSongError(SongError.java:124)",
    "bio.overture.song.core.exceptions.ServerException.buildServerException(ServerException.java:46)",
    "bio.overture.song.core.exceptions.ServerException.checkServer(ServerException.java:59)",
    "bio.overture.song.server.service.AnalysisService.checkMissingFiles(AnalysisService.java:455)",
    "bio.overture.song.server.service.AnalysisService.publish(AnalysisService.java:384)",
    "bio.overture.song.server.service.AnalysisService$$FastClassBySpringCGLIB$$7681c8ae.invoke(<generated>)",
    "org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)",
    "org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)",
    "org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)",
    "org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)",
    "org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)",
    "org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)",
    "org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)",
    "bio.overture.song.server.service.AnalysisService$$EnhancerBySpringCGLIB$$e8fe0ddf.publish(<generated>)",
    "bio.overture.song.server.controller.AnalysisController.publishAnalysis(AnalysisController.java:110)",
    "bio.overture.song.server.controller.AnalysisController$$FastClassBySpringCGLIB$$b8162298.invoke(<generated>)",
    "org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)",
    "org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)",
    "org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)",
    "org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)",
    "org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)",
    "org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)",
    "bio.overture.song.server.controller.AnalysisController$$EnhancerBySpringCGLIB$$49572925.publishAnalysis(<generated>)",
    "sun.reflect.GeneratedMethodAccessor495.invoke(Unknown Source)",
    "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
    "java.lang.reflect.Method.invoke(Method.java:498)",
    "org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)",
    "org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)",
    "org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)",
    "org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)",
    "org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)",
    "org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)",
    "org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)",
    "org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)",
    "org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)",
    "org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:888)",
    "javax.servlet.http.HttpServlet.service(HttpServlet.java:664)",
    "org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)",
    "javax.servlet.http.HttpServlet.service(HttpServlet.java:742)",
    "org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)",
    "org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)",
    "org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
    "org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:158)",
    "org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:126)",
    "org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:111)",
    "org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
    "org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
    "org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:84)",
    "org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
    "org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
    "org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)",
    "org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)",
    "org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)",
    "org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)",
    "org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)",
    "org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)",
    "org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)",
    "org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)",
    "org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:176)",
    "org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)",
    "org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)",
    "org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
    "org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)",
    "org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)",
    "org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
    "org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)",
    "org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)",
    "org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)",
    "org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)",
    "org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)",
    "org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
    "org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)",
    "org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
    "org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
    "org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)",
    "org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
    "org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
    "org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)",
    "org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
    "org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
    "org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)",
    "org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
    "org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)",
    "org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)",
    "org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)",
    "org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)",
    "org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)",
    "org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)",
    "org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)",
    "org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)",
    "org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)",
    "org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)",
    "org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)",
    "org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)",
    "org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)",
    "org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)",
    "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
    "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
    "org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)",
    "java.lang.Thread.run(Thread.java:748)"
  ]
}

**Comment by rtisma** [comment]
related to #129

**Comment by Buwujiu** [comment]
Issue fixed under #129.
