### ISSUE TITLE
BUG - Error when uploading files: "stateDir is marked @NonNull but is null"

### ISSUE THREAD

**Issue by hknahal** [overture-stack/score#274]
Receive an error ("stateDir is marked @NonNull but is null") when trying to upload files to Collab using score-client version 5.1.0.

## Description
One of the steps in the EGA File transfer process (transferring files from EGA to Collab) involves uploading the EGA files to Collab. This step used to work, but when the score-client was updated to the current version, an error occurs.

## Steps to Reproduce

Ran the following command:
```
~/score-client-5.1.0/bin/score-client upload --manifest manifest.txt --force
```
**Output:**
```
WARN: Object 54e9dbd9-45ba-5a6b-a0c6-08953a50415e exists and --force specified. Overwriting...                                                                                                               
Uploading object: '030fcacde1a5e653ac376f7b58b71dcb.CME_0001_Pa_C.bam' using the object id 54e9dbd9-45ba-5a6b-a0c6-08953a50415e
ERROR: Command error: stateDir is marked @NonNull but is null                                                                                                                                                

Please check the log for detailed error messages
```

**Details from error log:**

```
2020-08-28 13:21:48,590 [main] INFO  b.o.s.c.ClientMain - Started ClientMain in 2.132 seconds (JVM running for 3.113)
2020-08-28 13:21:49,452 [main] INFO  b.o.s.c.c.UploadCommand - Uploading file '030fcacde1a5e653ac376f7b58b71dcb.CME_0001_Pa_C.bam'...
2020-08-28 13:21:49,793 [main] INFO  b.o.s.c.u.s.S3UploadService - Start a new upload...
2020-08-28 13:21:51,687 [main] ERROR b.o.s.c.ClientMain - Unknown error:
java.lang.NullPointerException: stateDir is marked @NonNull but is null
        at bio.overture.score.client.state.TransferState.getObjectStateDir(TransferState.java:58)
        at bio.overture.score.client.upload.UploadStateStore.create(UploadStateStore.java:67)
        at bio.overture.score.client.upload.s3.S3UploadService.startUpload(S3UploadService.java:116)
        at bio.overture.score.client.upload.s3.S3UploadService.upload(S3UploadService.java:85)
        at bio.overture.score.client.command.UploadCommand.uploadFile(UploadCommand.java:116)
        at bio.overture.score.client.command.UploadCommand.execute(UploadCommand.java:90)
        at bio.overture.score.client.ClientMain.run(ClientMain.java:134)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:779)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:763)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:318)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
        at bio.overture.score.client.ClientMain.main(ClientMain.java:107)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:86)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**Manifest**:
```
EGAZ00001257788
54e9dbd9-45ba-5a6b-a0c6-08953a50415e    030fcacde1a5e653ac376f7b58b71dcb.CME_0001_Pa_C.bam      030fcacde1a5e653ac376f7b58b71dcb
1f6102fd-b77c-504b-b48f-a50e173826c3    030fcacde1a5e653ac376f7b58b71dcb.CME_0001_Pa_C.bam.bai  d72707072ca70a8b54cca404e1182877
86669756-a344-51cf-a47d-98360ed8163f    bundle.EGAZ00001257788.xml      176762a008729bbb49cbff5360f70744
```

**SONG payload** (unpublished): https://song.cancercollaboratory.org/studies/PACA-CA/analysis/EGAZ00001257788

## Your Environment

* Version used: 5.1.0
* VM: 10.0.0.13 (Ubuntu)

**Comment by rtisma** [comment]
@hknahal its seems the song-client was not used to generate the manifest. Try again using the song-client
```bash
./sing -a EGAZ00001257788 -f manifest.txt -d /path/to/dir/containing/files
```

**Comment by hknahal** [comment]
@rtisma I'm actually running score in a docker. I used the song-client to generate the manifest which actually looks like this: 
```
EGAZ00001257788		
54e9dbd9-45ba-5a6b-a0c6-08953a50415e	/app/030fcacde1a5e653ac376f7b58b71dcb.CME_0001_Pa_C.bam	030fcacde1a5e653ac376f7b58b71dcb
1f6102fd-b77c-504b-b48f-a50e173826c3	/app/030fcacde1a5e653ac376f7b58b71dcb.CME_0001_Pa_C.bam.bai	d72707072ca70a8b54cca404e1182877
86669756-a344-51cf-a47d-98360ed8163f	/app/bundle.EGAZ00001257788.xml	176762a008729bbb49cbff5360f70744
```
When I try to upload, it hangs for a while on `0% [#.....]` but eventually fails with this error message:

```
score-client upload --manifest /app/manifest.txt --force
Uploading object: '/app/030fcacde1a5e653ac376f7b58b71dcb.CME_0001_Pa_C.bam' using the object id 54e9dbd9-45ba-5a6b-a0c6-08953a50415e                                                                         
  0% [# ................................................]  Parts: 0/21, Checksum: 100%, Write/sec: 406.2M/s, Read/sec: 0B/s    
Finalizing...
ERROR: Data transfer has been interrupted. Some parts are missing. Waiting to retry...
Total execution time:         51.56 s
Total bytes read    :               0
Total bytes written :  21,961,637,577
ERROR: Command error: java.io.IOException:
```

The client.log shows a lot of "2020-08-28 17:22:07,968 [main] DEBUG b.o.s.c.t.MemoryMappedParallelPartObjectTransport - Memory is low. Wait..." errors:

```
2020-08-28 17:22:07,968 [main] DEBUG b.o.s.c.t.MemoryMappedParallelPartObjectTransport - Memory is low. Wait...
2020-08-28 17:22:07,978 [main] DEBUG b.o.s.c.t.MemoryMappedParallelPartObjectTransport - Memory is low. Wait...
2020-08-28 17:22:07,988 [main] DEBUG b.o.s.c.t.MemoryMappedParallelPartObjectTransport - Memory is low. Wait...
2020-08-28 17:22:07,998 [main] DEBUG b.o.s.c.t.MemoryMappedParallelPartObjectTransport - Memory is low. Wait...
2020-08-28 17:22:08,008 [main] DEBUG b.o.s.c.t.MemoryMappedParallelPartObjectTransport - Memory is low. Wait...
2020-08-28 17:22:08,018 [main] DEBUG b.o.s.c.t.MemoryMappedParallelPartObjectTransport - Memory is low. Wait...
2020-08-28 17:22:08,028 [main] DEBUG b.o.s.c.t.MemoryMappedParallelPartObjectTransport - Memory is low. Wait...
2020-08-28 17:22:08,038 [main] DEBUG b.o.s.c.t.MemoryMappedParallelPartObjectTransport - Memory is low. Wait...
2020-08-28 17:22:08,047 [pool-1-thread-1] DEBUG o.s.w.c.RestTemplate - Response 500 INTERNAL_SERVER_ERROR
2020-08-28 17:22:08,048 [pool-1-thread-1] WARN  b.o.s.c.e.AmazonS3RetryableResponseErrorHandler - Server error. Stop processing: Internal Server Error
2020-08-28 17:22:08,048 [pool-1-thread-1] ERROR b.o.s.c.s.s.ScoreStorageService - Could not proceed. Failed to send part for part number: 16
bio.overture.score.client.exception.NotResumableException: java.io.IOException:
        at bio.overture.score.client.exception.ControlExceptionFactory.notResumableException(ControlExceptionFactory.java:53)
        at bio.overture.score.client.exception.ControlExceptionFactory.notResumableException(ControlExceptionFactory.java:47)
        at bio.overture.score.client.exception.AmazonS3RetryableResponseErrorHandler.handleError(AmazonS3RetryableResponseErrorHandler.java:51)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:710)
        at bio.overture.score.client.storage.score.ScoreStorageService$2.doWithRetry(ScoreStorageService.java:153)
        at bio.overture.score.client.storage.score.ScoreStorageService$2.doWithRetry(ScoreStorageService.java:135)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:263)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:154)
        at bio.overture.score.client.storage.score.ScoreStorageService.uploadPart(ScoreStorageService.java:135)
        at bio.overture.score.client.transport.MemoryMappedParallelPartObjectTransport$1.call(MemoryMappedParallelPartObjectTransport.java:117)
        at bio.overture.score.client.transport.MemoryMappedParallelPartObjectTransport$1.call(MemoryMappedParallelPartObjectTransport.java:99)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException:
        ... 18 common frames omitted
2020-08-28 17:22:08,048 [pool-1-thread-1] DEBUG o.s.r.s.RetryTemplate - Checking for rethrow: count=1
2020-08-28 17:22:08,048 [pool-1-thread-1] DEBUG o.s.r.s.RetryTemplate - Retry failed last attempt: count=1
2020-08-28 17:22:08,049 [main] DEBUG b.o.s.c.t.MemoryMappedParallelPartObjectTransport - thread pool shut down request ...
2020-08-28 17:22:09,531 [pool-1-thread-2] DEBUG o.s.w.c.RestTemplate - Response 500 INTERNAL_SERVER_ERROR
2020-08-28 17:22:09,532 [pool-1-thread-2] WARN  b.o.s.c.e.AmazonS3RetryableResponseErrorHandler - Server error. Stop processing: Internal Server Error
2020-08-28 17:22:09,532 [pool-1-thread-2] ERROR b.o.s.c.s.s.ScoreStorageService - Could not proceed. Failed to send part for part number: 17
bio.overture.score.client.exception.NotResumableException: java.io.IOException:
        at bio.overture.score.client.exception.ControlExceptionFactory.notResumableException(ControlExceptionFactory.java:53)
        at bio.overture.score.client.exception.ControlExceptionFactory.notResumableException(ControlExceptionFactory.java:47)
        at bio.overture.score.client.exception.AmazonS3RetryableResponseErrorHandler.handleError(AmazonS3RetryableResponseErrorHandler.java:51)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:710)
        at bio.overture.score.client.storage.score.ScoreStorageService$2.doWithRetry(ScoreStorageService.java:153)
        at bio.overture.score.client.storage.score.ScoreStorageService$2.doWithRetry(ScoreStorageService.java:135)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:263)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:154)
        at bio.overture.score.client.storage.score.ScoreStorageService.uploadPart(ScoreStorageService.java:135)
        at bio.overture.score.client.transport.MemoryMappedParallelPartObjectTransport$1.call(MemoryMappedParallelPartObjectTransport.java:117)
        at bio.overture.score.client.transport.MemoryMappedParallelPartObjectTransport$1.call(MemoryMappedParallelPartObjectTransport.java:99)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
Do you know what this means? Is the BAM file too big to upload?

**Comment by hknahal** [comment]
I tried uploading a smaller file (XML file) and score reacts differently. It doesn't throw an error like it did when trying to upload the BAM file (above comment). Instead it just hangs like this:

```
root@577e9371d49e:/# score-client upload --manifest /app/manifest.txt --force
Uploading object: '/app/bundle.EGAZ00001257788.xml' using the object id 86669756-a344-51cf-a47d-98360ed8163f                                                                  
  0% [# ................................................]  Parts: 0/1, Checksum: 100%, Write/sec: 82.0K/s, Read/sec: 0B/s 
```

Here is part of the score client.log. I see a "Response 503 SERVICE_UNAVAILABLE" message but it's not clear what is failing. I'm using the same storage url (https://storage.cancercollaboratory.org:443) and metadata url (https://song.cancercollaboratory.org) as we've done in the past.

```
2020-08-28 19:29:03,142 [main] INFO  b.o.s.c.ClientMain - Started ClientMain in 1.878 seconds (JVM running for 2.68)
2020-08-28 19:29:03,186 [main] DEBUG o.s.w.c.RestTemplate - HTTP GET https://storage.cancercollaboratory.org:443/download/ping
2020-08-28 19:29:03,191 [main] DEBUG o.s.w.c.RestTemplate - Accept=[text/plain, application/json, application/cbor, application/*+json, */*]
2020-08-28 19:29:03,423 [main] DEBUG o.s.w.c.RestTemplate - Response 200 OK
2020-08-28 19:29:03,424 [main] DEBUG o.s.w.c.RestTemplate - Reading to [java.lang.String] as "text/plain;charset=UTF-8"
2020-08-28 19:29:03,430 [main] DEBUG o.s.w.c.RestTemplate - HTTP GET https://object.cancercollaboratory.org:9080/oicr.icgc/data/heliograph?AWSAccessKeyId=HHX5RO7K5Z48HZJH8Y23&Expires=1598643243&Signature=f6M6sf6Wg3Pqp3qJ9jpCFWetUsE%3D
2020-08-28 19:29:03,430 [main] DEBUG o.s.w.c.RestTemplate - Accept=[text/plain, application/json, application/cbor, application/*+json, */*]
2020-08-28 19:29:03,474 [main] DEBUG o.s.w.c.RestTemplate - Response 200 OK
2020-08-28 19:29:03,474 [main] DEBUG o.s.w.c.RestTemplate - Reading to [java.lang.String] as "binary/octet-stream"
2020-08-28 19:29:03,492 [main] INFO  b.o.s.c.c.UploadCommand - Uploading file '/app/bundle.EGAZ00001257788.xml'...
2020-08-28 19:29:03,492 [main] DEBUG b.o.s.c.s.s.ScoreStorageService - Checking existence on Storage server for object-id: 86669756-a344-51cf-a47d-98360ed8163f
2020-08-28 19:29:03,494 [main] TRACE o.s.r.s.RetryTemplate - RetryContext retrieved: [RetryContext: count=0, lastException=null, exhausted=false]
2020-08-28 19:29:03,495 [main] DEBUG o.s.r.s.RetryTemplate - Retry: count=0
2020-08-28 19:29:03,496 [main] DEBUG o.s.w.c.RestTemplate - HTTP GET https://storage.cancercollaboratory.org:443/upload/86669756-a344-51cf-a47d-98360ed8163f
2020-08-28 19:29:03,497 [main] DEBUG o.s.w.c.RestTemplate - Accept=[application/json, application/cbor, application/*+json]
2020-08-28 19:29:03,566 [main] DEBUG o.s.w.c.RestTemplate - Response 200 OK
2020-08-28 19:29:03,567 [main] DEBUG o.s.w.c.RestTemplate - Reading to [java.lang.Boolean]
2020-08-28 19:29:03,578 [main] INFO  b.o.s.c.u.s.S3UploadService - Start a new upload...
2020-08-28 19:29:03,578 [main] DEBUG b.o.s.c.s.s.ScoreStorageService - Initiating upload, object-id: 86669756-a344-51cf-a47d-98360ed8163f overwrite: true
2020-08-28 19:29:03,580 [main] TRACE o.s.r.s.RetryTemplate - RetryContext retrieved: [RetryContext: count=0, lastException=null, exhausted=false]
2020-08-28 19:29:03,580 [main] DEBUG o.s.r.s.RetryTemplate - Retry: count=0
2020-08-28 19:29:03,583 [main] DEBUG o.s.w.c.RestTemplate - HTTP POST https://storage.cancercollaboratory.org:443/upload/86669756-a344-51cf-a47d-98360ed8163f/uploads?fileSize=4135&overwrite=true&md5=176762a008729bbb49cbff5360f70744
2020-08-28 19:29:03,616 [main] DEBUG o.s.w.c.RestTemplate - Accept=[application/json, application/cbor, application/*+json]
2020-08-28 19:29:07,012 [main] DEBUG o.s.w.c.RestTemplate - Response 200 OK
2020-08-28 19:29:07,013 [main] DEBUG o.s.w.c.RestTemplate - Reading to [bio.overture.score.core.model.ObjectSpecification]
2020-08-28 19:29:07,016 [main] DEBUG b.o.s.c.s.TransferState - About to delete /app/.86669756-a344-51cf-a47d-98360ed8163f
2020-08-28 19:29:07,019 [main] DEBUG b.o.s.c.s.TransferState - About to re-create /app/.86669756-a344-51cf-a47d-98360ed8163f
2020-08-28 19:29:07,034 [main] DEBUG b.o.s.c.t.MemoryMappedParallelPartObjectTransport - Transport Settings: ParallelPartObjectTransport.RemoteParallelBuilder(nThreads=6, memory=5368709120, maxUploadDuration=2147483647)
2020-08-28 19:29:07,034 [main] DEBUG b.o.s.c.t.MemoryMappedParallelPartObjectTransport - send file: /app/bundle.EGAZ00001257788.xml
2020-08-28 19:29:07,038 [main] DEBUG b.o.s.c.t.MemoryMappedParallelPartObjectTransport - Submitting new Callable task
2020-08-28 19:29:07,039 [main] DEBUG b.o.s.c.t.MemoryMappedParallelPartObjectTransport - Remaining Memory : 5368704985
2020-08-28 19:29:07,039 [main] DEBUG b.o.s.c.t.MemoryMappedParallelPartObjectTransport - Number of submitted tasks : 1
2020-08-28 19:29:07,039 [main] DEBUG b.o.s.c.t.MemoryMappedParallelPartObjectTransport - thread pool shut down request ...
2020-08-28 19:29:07,045 [pool-1-thread-1] INFO  b.o.s.c.t.MemoryMappedParallelPartObjectTransport - Sending remaining part Part(partNumber=1, partSize=4135, offset=0, url=https://object.cancercollaboratory.org:9080/oicr.icgc.6/data/86669756-a344-51cf-a47d-98360ed8163f?uploadId=2~XqkgiTboLUqhuDgH_OdWVcxbbX_2cPd&partNumber=1&AWSAccessKeyId=HHX5RO7K5Z48HZJH8Y23&Expires=1599161343&Signature=4%2BbC9KR6GodeT8WYXYPDshkT1tg%3D, md5=null, sourceMd5=null)
2020-08-28 19:29:07,067 [pool-1-thread-1] TRACE o.s.r.s.RetryTemplate - RetryContext retrieved: [RetryContext: count=0, lastException=null, exhausted=false]
2020-08-28 19:29:07,067 [pool-1-thread-1] DEBUG o.s.r.s.RetryTemplate - Retry: count=0
2020-08-28 19:29:07,067 [pool-1-thread-1] DEBUG b.o.s.c.s.s.ScoreStorageService - Upload Part URL: https://object.cancercollaboratory.org:9080/oicr.icgc.6/data/86669756-a344-51cf-a47d-98360ed8163f?uploadId=2~XqkgiTboLUqhuDgH_OdWVcxbbX_2cPd&partNumber=1&AWSAccessKeyId=HHX5RO7K5Z48HZJH8Y23&Expires=1599161343&Signature=4%2BbC9KR6GodeT8WYXYPDshkT1tg%3D
2020-08-28 19:29:07,075 [pool-1-thread-1] DEBUG o.s.w.c.RestTemplate - HTTP PUT https://object.cancercollaboratory.org:9080/oicr.icgc.6/data/86669756-a344-51cf-a47d-98360ed8163f?uploadId=2~XqkgiTboLUqhuDgH_OdWVcxbbX_2cPd&partNumber=1&AWSAccessKeyId=HHX5RO7K5Z48HZJH8Y23&Expires=1599161343&Signature=4%2BbC9KR6GodeT8WYXYPDshkT1tg%3D
2020-08-28 19:29:07,204 [pool-1-thread-1] DEBUG o.s.w.c.RestTemplate - Response 200 OK
2020-08-28 19:29:07,205 [pool-1-thread-1] DEBUG b.o.s.c.s.s.ScoreStorageService - Finalizing upload part, object-id: 86669756-a344-51cf-a47d-98360ed8163f, upload-id: 2~XqkgiTboLUqhuDgH_OdWVcxbbX_2cPd, part-number: 1
2020-08-28 19:29:07,207 [pool-1-thread-1] TRACE o.s.r.s.RetryTemplate - RetryContext retrieved: [RetryContext: count=0, lastException=null, exhausted=false]
2020-08-28 19:29:07,207 [pool-1-thread-1] DEBUG o.s.r.s.RetryTemplate - Retry: count=0
2020-08-28 19:29:07,208 [pool-1-thread-1] DEBUG o.s.w.c.RestTemplate - HTTP POST https://storage.cancercollaboratory.org:443/upload/86669756-a344-51cf-a47d-98360ed8163f/parts?uploadId=2~XqkgiTboLUqhuDgH_OdWVcxbbX_2cPd&partNumber=1&md5=176762a008729bbb49cbff5360f70744&etag=176762a008729bbb49cbff5360f70744
2020-08-28 19:29:07,212 [pool-1-thread-1] DEBUG o.s.w.c.RestTemplate - Accept=[application/json, application/cbor, application/*+json]
2020-08-28 19:29:07,959 [pool-1-thread-1] DEBUG o.s.w.c.RestTemplate - Response 503 SERVICE_UNAVAILABLE
2020-08-28 19:29:07,960 [pool-1-thread-1] WARN  b.o.s.c.e.ServiceRetryableResponseErrorHandler - Retryable exception:
2020-08-28 19:29:07,975 [pool-1-thread-1] DEBUG o.s.r.b.ExponentialBackOffPolicy - Sleeping for 100
2020-08-28 19:29:08,075 [pool-1-thread-1] DEBUG o.s.r.s.RetryTemplate - Checking for rethrow: count=1
2020-08-28 19:29:08,075 [pool-1-thread-1] DEBUG o.s.r.s.RetryTemplate - Retry: count=1
2020-08-28 19:29:08,076 [pool-1-thread-1] DEBUG o.s.w.c.RestTemplate - HTTP POST https://storage.cancercollaboratory.org:443/upload/86669756-a344-51cf-a47d-98360ed8163f/parts?uploadId=2~XqkgiTboLUqhuDgH_OdWVcxbbX_2cPd&partNumber=1&md5=176762a008729bbb49cbff5360f70744&etag=176762a008729bbb49cbff5360f70744
2020-08-28 19:29:08,077 [pool-1-thread-1] DEBUG o.s.w.c.RestTemplate - Accept=[application/json, application/cbor, application/*+json]
2020-08-28 19:29:09,850 [pool-1-thread-1] DEBUG o.s.w.c.RestTemplate - Response 503 SERVICE_UNAVAILABLE
2020-08-28 19:29:09,851 [pool-1-thread-1] WARN  b.o.s.c.e.ServiceRetryableResponseErrorHandler - Retryable exception:
2020-08-28 19:29:09,852 [pool-1-thread-1] DEBUG o.s.r.b.ExponentialBackOffPolicy - Sleeping for 200
2020-08-28 19:29:10,052 [pool-1-thread-1] DEBUG o.s.r.s.RetryTemplate - Checking for rethrow: count=2
2020-08-28 19:29:10,052 [pool-1-thread-1] DEBUG o.s.r.s.RetryTemplate - Retry: count=2
2020-08-28 19:29:10,053 [pool-1-thread-1] DEBUG o.s.w.c.RestTemplate - HTTP POST https://storage.cancercollaboratory.org:443/upload/86669756-a344-51cf-a47d-98360ed8163f/parts?uploadId=2~XqkgiTboLUqhuDgH_OdWVcxbbX_2cPd&partNumber=1&md5=176762a008729bbb49cbff5360f70744&etag=176762a008729bbb49cbff5360f70744
2020-08-28 19:29:10,054 [pool-1-thread-1] DEBUG o.s.w.c.RestTemplate - Accept=[application/json, application/cbor, application/*+json]
2020-08-28 19:29:11,851 [pool-1-thread-1] DEBUG o.s.w.c.RestTemplate - Response 503 SERVICE_UNAVAILABLE
2020-08-28 19:29:11,851 [pool-1-thread-1] WARN  b.o.s.c.e.ServiceRetryableResponseErrorHandler - Retryable exception:
2020-08-28 19:29:11,852 [pool-1-thread-1] DEBUG o.s.r.b.ExponentialBackOffPolicy - Sleeping for 400
2020-08-28 19:29:12,253 [pool-1-thread-1] DEBUG o.s.r.s.RetryTemplate - Checking for rethrow: count=3
2020-08-28 19:29:12,253 [pool-1-thread-1] DEBUG o.s.r.s.RetryTemplate - Retry: count=3
```
